### ISSUE TITLE
broken update script updatewebui.sh

### ISSUE THREAD

**Issue by CapnRon** [OpenIPC/webui#239]
updatewebui.sh is pulling from "/OpenIPC/microbe-web/archive/refs/heads" instead of "/OpenIPC/webui/archive/refs/heads/". Changing that block as listed below allows more current update on master

```
if [ -n "$branch" ]; then
        url="https://github.com/OpenIPC/webui/archive/refs/heads/${branch}.zip"
        bundle_dir="webui-${branch}"
elif [ -n "$commit" ]; then
        url="https://github.com/OpenIPC/webui/archive/${commit}.zip"
        bundle_dir="webui-${commit}"
else
        echo_c 31 "branch: ${branch}, commit: ${commit}"
        echo_c 33 "You need to specify either a branch or a commit hash!"
        print_usage
        exit 0
fi
```

**Comment by viktorxda** [comment]
The repo was just renamed, but the old link should still work for a while to allow updating from older version.

Both resulting files are identical:
- https://github.com/OpenIPC/webui/archive/refs/heads/master.zip
- https://github.com/OpenIPC/microbe-web/archive/refs/heads/master.zip
