### ISSUE TITLE
Setting static ip for eth0 not working for version 2.4.01.05-fpv of firmware openipc-ssc338q-fpv-16mb.bin

### ISSUE THREAD

**Issue by mebj** [OpenIPC/webui#241]
Igor Zalatov has recommended that I file a request for this issue.

My camera is a ssc338 and I have installed different versions of openipc-ssc338q-fpv-16mb.bin as time went. Using webui I have changed the IP obtained by dhcp to a static address and this has worked well until version 2.4.01.05-fpv with build: master+48089e5, 2024-01-05.

With this version the change to a static address for eth0 seems to work but after saving new data the old dhcp generated address is back in the settings placeholders. After rebooting the eth0 interface no longer can be reached (not even pinged) at the new static address nor at the previous dhcp generated one. Only way to recover is to reset to pristine condition or reinstall firmware.

Enclosed screenshots show my data before before and after saving the static address.
![2](https://github.com/OpenIPC/webui/assets/10342504/64a128a6-3532-42a8-b5dc-9e602da8ba51)
![3](https://github.com/OpenIPC/webui/assets/10342504/3d9f7fa9-b122-44ad-b722-043c36e7674c)

**Comment by viktorxda** [comment]
A fix was applied, please update to the dev branch for now.
You can re-open the ticket if there is still an issue.
