### ISSUE TITLE
WebUI: Network config, DNS inserts linebreak, invalid config prevents network device from coming up on reboot

### ISSUE THREAD

**Issue by LukeO1982** [OpenIPC/webui#247]
Dear Team,

Settings -> Network -> Set static IP, and DNS -> Save changes:
inserts a linebreak on the last line:

>   pre-up echo -e "nameserver 1.1.1.1
> " >/tmp/resolv.conf

this should be:
>    pre-up echo -e "nameserver 1.1.1.1" >/tmp/resolv.conf

This config is committed to file  /etc/network/interfaces.d/<device_id> and fails to be read on reboot, make the network interface unconfigured/unavailable.

Output is similar, and wrong, when setting 2 DNS:

> pre-up echo -e "nameserver 1.1.1.1
> nameserver 8.8.8.8
> " >/tmp/resolv.conf

Thanks and cheers

**System info:**
On Firefox browser and 
Hardware: ssc337de
Family:  infinity6b0

# cat /etc/os-release
NAME=Buildroot
VERSION=-ga5f2697
ID=buildroot
VERSION_ID=2023.02.7
PRETTY_NAME="Buildroot 2023.02.7"
OPENIPC_VERSION=2.4.01.17
GITHUB_VERSION="master+a5f2697, 2024-01-17"
BUILD_OPTION=ultimate
TIME_STAMP=1705461130

**Comment by LukeO1982** [comment]
Additional info on error indication:

> /etc/init.d/S40network restart
> Stopping network...
> Starting network...
> /bin/sh: syntax error: unterminated quoted string

**Comment by LukeO1982** [comment]
Culprint: 

webui/files/usr/sbin/setnetiface.sh

https://github.com/OpenIPC/webui/blob/f0404c9681eff90b75417fa56e49f772718dc3b6/files/usr/sbin/setnetiface.sh#L186C1-L186C56

Potential solution:
change
`printf "nameserver %s\n" "$dns" >>"$tmp_config_file"`
to
`printf "nameserver %s" "$dns\\n" >>"$tmp_config_file"`
so tmp file contains literal newline "\n" indicators, that "echo -e " processes into linebreaks

**Comment by themactep** [comment]
The DNS directive is already changed in the development branch. Please update you web ui to development version and confirm that it fixes the issue for you.

**Comment by LukeO1982** [comment]
Confirmed fix in dev brach works. Issue closed
