### ISSUE TITLE
/var/www/cgi-bin/network.cgi doesn't actually modify WLAN SSID and PSK

### ISSUE THREAD

**Issue by plush** [OpenIPC/webui#264]
On the /var/www/cgi-bin/network.cgi page, you can select an interface (e.g. wlan0) and set its WLAN SSID and PSK. The initial values are read from the firmware environment variables `wlanssid` and `wlanpass`. Hoewever, they are never written back to the environment, so hitting "Save changes" simply does nothing. The only way I found to change WiFi settings is via the console and `fw_setenv`.

**Comment by FlyRouter** [comment]
Good afternoon, thank you for your interest in the project.
This is an experimental setting and you can send a patch with corrections, we will be grateful. Also take a look at the alternative webui-next thread to keep up to date with new ideas.

**Comment by a-sakharov** [comment]
Fixed with #268

**Comment by FlyRouter** [comment]
Merged, thank you
